Project/urls.py
from django.contrib import admin
from django.urls import path, include
from layout import views

urlpatterns = [
    path('', views.index, name='index'),
    path('', include('layout.urls')),
    path('admin/', admin.site.urls),
    path('', include('videos.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

layout/urls.py
from django.urls import path

from . import views

app_name = 'layout'

urlpatterns = [
    path('', views.index, name='index'),
]

videos/urls.py
from .views import video, vote, search_videos, view_comments, create_comment, delete_comment, delete_tag
from django.urls import path

app_name = 'videos'

urlpatterns = [
    path('videos/<int:identifier>/', video, name='video'),
    path('videos/vote/', vote, name='vote'),
    path('videos/search/', search_videos, name='search'),
    path('videos/comments/', view_comments, name='comment'),
    path('videos/create_comment/', create_comment, name='create_comment'),
    path('videos/delete_comment/', delete_comment, name='delete_comment'),
    path('videos/delete_tag/', delete_tag, name='delete_tag'),
]

layout/models.py
from django.db import models

# Create your models here.

layout/views.py
from django.shortcuts import render

from videos.models import Video


def index(request):
    obj = Video.objects.all()
    return render(request, 'layout/index.html', {'obj': obj})

templates/layout/base.html
<!DOCTYPE html>
{% load static %}
{% load custom_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TAGV</title>
    <script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/layout.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bootbox/4.4.0/bootbox.min.js"></script>
    <script type="text/javascript">var user_messages = {{ messages | message_to_list | safe }}</script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <script src="{% static 'js/userMessageControl.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: rgb(73, 113, 170)">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static "images/logo.png" %}" class="rounded float-start" alt="" id="logo">
        </a>
        <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
            &#9776;
        </button>
        <div class="collapse navbar-collapse" id="exCollapsingNavbar">
            <ul class="nav navbar-nav">
                <li class="nav-item"><a href="{% url 'accounts:register' %}" class="nav-link" style="color: rgb(73, 113, 170)" >s</a></li>


                {% if not 'videos/' in request.path %}
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search" id="search-bar"
                               oninput=sendSearchRequest() step="0.01">
                    </div>
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </form>
                {% endif %}

            </ul>
            <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a href="#" class="nav-link">{{ user.username }}</a></li>
                {% endif %}
                <li class="dropdown order-1">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link">Login</a></li>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>


</div>
</nav>

{% block body_block %}



    <!--- Anything outside of this will be inherited -->
{% endblock %}
</div>

<script src="{% static 'js/homePageVideo.js' %}"></script>

</body>
</html>

templates/layout/index.html
<!DOCTYPE html>
{% extends "layout/base.html" %}
{% load embed_video_tags %}
{% load static %}
{% block body_block %}

    {% if user.is_authenticated %}
        <body class="home">
        <div class="container p-4 bg-white">
            <div class="row" id="video-container">
                {% for i in obj %}
                    <div class="col-md-6 content-center" id="video-column">
                        <div class="bg-light border rounded" id="video">
                            <h1><a class="btn btn-link" href="{% url 'videos:video' i.id %}"> {{ i.name }} </a></h1>
                            <div class="video-responsive">
                                {% video i.video 'small' %}
                            </div>
                            <p><span class="badge bg-secondary text-light">{{ i.duration|time:'H:i:s' }}</span></p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        </body>

    {% else %}
        <body class="home">
        <div class="container justify-content-center" id="heading-home">
            <div class="p-2">
                <h1>Welcome to TAGV</h1>
                <p>A platform to watch videos, and more.</p>
                <p>TAGV allows you to put time stamps in your videos, for your use, and to help other viewers.</p>
            </div>
            <div class="p-2">
                <h4 id="login">Please login to watch videos, or register to create an account.</h4>
                <a class="btn btn-secondary" href="{% url 'accounts:login' %}" role="button">Login</a>
                <a class="btn btn-secondary" href="{% url 'accounts:register' %}" role="button">Register</a>
            </div>
        </div>
        </body>
    {% endif %}

    <link rel="stylesheet" href="{% static "css/videos.css" %}">
{% endblock %}